name: Basic Build Workflow

on:
  - pull_request
  - push

jobs:
  build-foxy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-ros-foxy-ros-base-testing-latest
    steps:
    - name: Fix Bugs in ros-tooling/action-ros-ci
      run: sudo chown -R rosbuild:rosbuild "$HOME" .
    - name: Run Tests
      uses: ros-tooling/action-ros-ci@0.2.0
      with:
        package-name: |
          joy
          joy_linux
          sdl2_vendor
          wiimote
          wiimote_msgs
        source-ros-binary-installation: foxy
        vcs-repo-file-url: ""
    - name: Upload logs
      uses: actions/upload-artifact@v1
      with:
        name: colcon-logs
        path: ros_ws/log
      if: always()
