name: Basic Build Workflow

on:
  - pull_request
  - push

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ros_distribution:
          - foxy
          - galactic
    container:
      image: ubuntu:focal
    steps:
    - uses: ros-tooling/setup-ros@v0.2
      with:
        required-ros-distributions: ${{ matrix.ros_distribution }}
    - name: Run Tests
      uses: ros-tooling/action-ros-ci@v0.2
      with:
        package-name: |
          joy
          joy_linux
          sdl2_vendor
          spacenav
          wiimote
          wiimote_msgs
        target-ros2-distro: ${{ matrix.ros_distribution }}
    - name: Upload logs
      uses: actions/upload-artifact@v1
      with:
        name: colcon-logs
        path: ros_ws/log
      if: always()
