name: Jazzy Build

on:
  - pull_request
  - push

jobs:
  build-rolling:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-ros-jazzy-desktop-latest
    steps:
    - name: Build Environment
      uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: jazzy
    - name: Run Tests
      uses: ros-tooling/action-ros-ci@v0.3
      id: jazzy_action_ros_ci_step
      with:
        package-name: |
          joy
          joy_linux
          sdl2_vendor
          spacenav
          wiimote
          wiimote_msgs
        target-ros2-distro: jazzy
    - name: Upload logs
      uses: actions/upload-artifact@v4
      with:
        name: colcon-logs
        path: ${{ steps.jazzy_action_ros_ci_step.outputs.ros-workspace-directory-name }}/log
      if: always()
